name: Simple services
services:
  web:
    image: nginx:latest
    container_name: simple-nginx
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    image: php:8.1-fpm
    container_name: simple-php-fpm
    volumes:
      - ./:/var/www/html