name: Simple services
services:
  web:
    image: nginx:latest
    container_name: simple-nginx
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    image: php:8.1-fpm
    container_name: simple-php-fpm
    volumes:
      - ./:/var/www/html
  db:
    image: mariadb
    container_name: simple-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple_db
      MYSQL_USER: simple_user
      MYSQL_PASSWORD: simple_password
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql

volumes:
    data: