name: Quality
on:
  push:
    branches:
      - master
      - main
  pull_request:
      types: [opened, synchronize]
      branches:
        - master
        - main

jobs:
  composer-validate:
    name: Validate composer.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Composer validate
        run: composer validate --strict
